#msg="Path Home" logger=settings path=/usr/share/grafana
#msg="Path Data" logger=settings path=/var/lib/grafana
#msg="Path Logs" logger=settings path=/var/log/grafana
#msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
#msg="Path Provisioning" logger=settings path=/etc/grafana/provisionin
version: '3'
services:
  grafana:
    container_name: grafana
    image: grafana/grafana
    user : "1000"
    ports:
    - "3000:3000"
    volumes:
      - /opt/grafana/data:/var/lib/grafana  
    networks:
      - net         
networks:
  net:

